name = "estate-podium"
compatibility_date = "2026-05-26"

pages_build_output_dir = "dist"

[vars]
NODE_ENV = "production"

[[d1_databases]]
binding = "DB"
database_name = "estate_podium_db"
database_id = "fcd30881-5e7e-4e04-b205-c3c8b2b63a9e"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "estate-images"
